# Generated by Django 5.2.16 on 2026-08-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
