# Generated by Codex on 2026-08-16

from decimal import Decimal
from django.db import migrations


THERAPIES = [
    {
        'name': 'Vamana',
        'description': 'Therapeutic emesis procedure used in Panchakarma care plans.',
        'duration': 60,
        'price': Decimal('1500.00'),
    },
    {
        'name': 'Virechana',
        'description': 'Guided purgation therapy for digestive and metabolic wellness support.',
        'duration': 60,
        'price': Decimal('1600.00'),
    },
    {
        'name': 'Basti',
        'description': 'Medicated enema therapy planned and monitored by trained practitioners.',
        'duration': 45,
        'price': Decimal('1400.00'),
    },
    {
        'name': 'Nasya',
        'description': 'Nasal therapy for head, neck, and respiratory wellness support.',
        'duration': 30,
        'price': Decimal('900.00'),
    },
    {
        'name': 'Raktamokshana',
        'description': 'Bloodletting-oriented Ayurvedic procedure delivered under clinical supervision.',
        'duration': 45,
        'price': Decimal('1800.00'),
    },
]


def seed_therapies(apps, schema_editor):
    Therapy = apps.get_model('bookings', 'Therapy')
    for item in THERAPIES:
        Therapy.objects.update_or_create(
            name=item['name'],
            defaults={
                'description': item['description'],
                'duration': item['duration'],
                'price': item['price'],
                'is_active': True,
            },
        )


def unseed_therapies(apps, schema_editor):
    Therapy = apps.get_model('bookings', 'Therapy')
    Therapy.objects.filter(name__in=[item['name'] for item in THERAPIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_therapies, unseed_therapies),
    ]
