# Generated by Django 5.2.16 on 2026-08-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_default_therapies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='applied', max_length=10),
        ),
    ]
