# Generated by Django 5.2.16 on 2026-08-19 11:51

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(validators=[bookings.models.validate_booking_date]),
        ),
    ]
